### ISSUE TITLE
Python - "links" function missing capability

### ISSUE THREAD

**Issue by elibenton** [seomoz/SEOmozAPISamples#38]
In the "mozscape.py" file, the links function does not include all possible parameters. Notably, the `Limit` and `Offset` parameters do not exist. Could these features be added, so use of the API for python developers does not require building another module from a third-party library like requests?

```python    
def links(
            self, url, scope='page_to_page', sort='page_authority',
            filters=['internal'],
            targetCols=(UMCols.url | UMCols.pageAuthority),
            sourceCols=(UMCols.url | UMCols.pageAuthority),
            linkCols=0):
        """This is currently broken. Have not figured it out"""
        return self.query(
            'links/%s' % quote(url),
            Scope=scope,
            Sort=sort,
            Filter='+'.join(filters),
            TargetCols=targetCols,
            SourceCols=sourceCols,
            LinkCols=linkCols)
```

Thank you for considering this request.

**Comment by b4hand** [comment]
FWIW, this code is not exactly production quality. It doesn't handle errors at all or do any retries, but I'll see what I can do.

**Comment by elibenton** [comment]
I understand the limited scope of this code, and really appreciate your consideration anyways!
